export const API_ERROR_TRANSLATION_KEYS = {
  AUTH_TOKEN_MISSING: "api_error.AUTH_TOKEN_MISSING",
  AUTH_INVALID_TOKEN: "api_error.AUTH_INVALID_TOKEN",
  AUTH_FORBIDDEN: "api_error.AUTH_FORBIDDEN",
  COMMON_NOT_FOUND: "api_error.COMMON_NOT_FOUND",
  COMMON_BAD_REQUEST: "api_error.COMMON_BAD_REQUEST",
  TD_RUN_LIMIT_EXCEEDED: "api_error.TD_RUN_LIMIT_EXCEEDED",
  TD_RUN_NOT_STARTED: "api_error.TD_RUN_NOT_STARTED",
  TD_RUN_TOO_FAST: "api_error.TD_RUN_TOO_FAST",
  QUEST_ALREADY_CLAIMED: "api_error.QUEST_ALREADY_CLAIMED",
  QUEST_NOT_COMPLETED: "api_error.QUEST_NOT_COMPLETED",
  REWARD_NOT_ENOUGH_POINTS: "api_error.REWARD_NOT_ENOUGH_POINTS",
  REWARD_INVALID_PRODUCT: "api_error.REWARD_INVALID_PRODUCT",
  REWARD_INVALID_QUANTITY: "api_error.REWARD_INVALID_QUANTITY",
  GACHA_NOT_ENOUGH_POINTS: "api_error.GACHA_NOT_ENOUGH_POINTS",
  GACHA_INVALID_EGG: "api_error.GACHA_INVALID_EGG",
  GACHA_NOT_ENOUGH_EGGS: "api_error.GACHA_NOT_ENOUGH_EGGS",
  GACHA_INVALID_BATCH_COUNT: "api_error.GACHA_INVALID_BATCH_COUNT",
  BREED_INVALID_RARITY: "api_error.BREED_INVALID_RARITY",
  BREED_NOT_ENOUGH_ESSENCE: "api_error.BREED_NOT_ENOUGH_ESSENCE",
  BREED_ALL_OWNED: "api_error.BREED_ALL_OWNED",
  AUCTION_NOT_FOUND: "api_error.AUCTION_NOT_FOUND",
  AUCTION_INVALID_CHARACTER: "api_error.AUCTION_INVALID_CHARACTER",
  AUCTION_INVALID_START_PRICE: "api_error.AUCTION_INVALID_START_PRICE",
  AUCTION_INVALID_BUYOUT_PRICE: "api_error.AUCTION_INVALID_BUYOUT_PRICE",
  AUCTION_INVALID_DURATION: "api_error.AUCTION_INVALID_DURATION",
  AUCTION_CHARACTER_NOT_OWNED: "api_error.AUCTION_CHARACTER_NOT_OWNED",
  AUCTION_TOO_MANY_ACTIVE_LISTINGS: "api_error.AUCTION_TOO_MANY_ACTIVE_LISTINGS",
  AUCTION_CANNOT_BID_OWN_LISTING: "api_error.AUCTION_CANNOT_BID_OWN_LISTING",
  AUCTION_CHARACTER_ALREADY_OWNED: "api_error.AUCTION_CHARACTER_ALREADY_OWNED",
  AUCTION_BID_TOO_LOW: "api_error.AUCTION_BID_TOO_LOW",
  AUCTION_NOT_ENOUGH_POINTS: "api_error.AUCTION_NOT_ENOUGH_POINTS",
  AUCTION_BID_OUTDATED: "api_error.AUCTION_BID_OUTDATED",
  AUCTION_BUYOUT_NOT_AVAILABLE: "api_error.AUCTION_BUYOUT_NOT_AVAILABLE",
  AUCTION_LISTING_ALREADY_ENDED: "api_error.AUCTION_LISTING_ALREADY_ENDED",
  AUCTION_LISTING_HAS_BID: "api_error.AUCTION_LISTING_HAS_BID",
  AUCTION_LISTING_ALREADY_SETTLED: "api_error.AUCTION_LISTING_ALREADY_SETTLED",
} as const;

export type ApiErrorCode = keyof typeof API_ERROR_TRANSLATION_KEYS;

export function getApiErrorCode(err: unknown): ApiErrorCode | undefined {
  const code = err instanceof Error ? (err as Error & { code?: string }).code : undefined;
  return code && code in API_ERROR_TRANSLATION_KEYS ? (code as ApiErrorCode) : undefined;
}

export function getApiErrorTranslationKey(err: unknown): string | undefined {
  const code = getApiErrorCode(err);
  return code ? API_ERROR_TRANSLATION_KEYS[code] : undefined;
}
